### ISSUE TITLE
 Exception java.lang.NoClassDefFoundError: com/lmax/disruptor/SequenceReportingEventHandler

### ISSUE THREAD

**Issue by IWareQ** [apache/logging-log4j2#1912]
## Description

No support for com.lmax disruptor 4.0.0

my libs.versions.toml:
```
log4j = "2.21.1"

disruptor = { group = "com.lmax", name = "disruptor", version = "4.0.0" }

slf4j-api = { group = "org.slf4j", name = "slf4j-api", version = "2.0.9" }
log4j-slf4j2-impl = { group = "org.apache.logging.log4j", name = "log4j-slf4j2-impl", version.ref = "log4j" }
log4j-core = { group = "org.apache.logging.log4j", name = "log4j-core", version.ref = "log4j" }
```

## Configuration

**Version:** 2.21.1

**Operating system:** Windows 11

**JDK:** 21 Azul

## Logs

```
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoClassDefFoundError: com/lmax/disruptor/SequenceReportingEventHandler [in thread "Test worker"]
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at org.apache.logging.log4j.core.async.AsyncLoggerDisruptor.start(AsyncLoggerDisruptor.java:123)
	at org.apache.logging.log4j.core.async.AsyncLoggerContext.start(AsyncLoggerContext.java:75)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:155)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:47)
	at org.apache.logging.log4j.LogManager.getContext(LogManager.java:196)
	at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getContext(AbstractLoggerAdapter.java:137)
	at org.apache.logging.slf4j.Log4jLoggerFactory.getContext(Log4jLoggerFactory.java:61)
	at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getLogger(AbstractLoggerAdapter.java:47)
	at org.apache.logging.slf4j.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:33)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:426)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:451)
	at cn.allay.api.AllayAPI.<clinit>(AllayAPI.java:43)
	... 55 more

```

**Comment by vy** [comment]
@IWareQ, thanks for the report, though this is a known issue. See #1829 or [LOG4J2-3595](https://issues.apache.org/jira/browse/LOG4J2-3595). There maintainers also share what needs to be done to fix the issue. We would appreciate it if you can submit a PR implementing the roadmap detailed there.
