### ISSUE TITLE
Java 21 error with LMAX

### ISSUE THREAD

**Issue by jkvargas** [apache/logging-log4j2#1962]
## Description

While using amazon correto 21 and running the following line:
final static Logger logger = LogManager.getLogger();

I guess it is related to LMAX...

## Configuration

**Version:** 2.21

**Operating system:** Linux

**JDK:** correto 21

## Logs

```
Exception in thread "main" java.lang.NoClassDefFoundError: sun/misc/Unsafe
    at com.lmax.disruptor.util.Util$1.run(Util.java:103)
    at com.lmax.disruptor.util.Util$1.run(Util.java:100)
    at java.base/java.security.AccessController.doPrivileged(Unknown Source)
    at com.lmax.disruptor.util.Util.<clinit>(Util.java:109)
    at com.lmax.disruptor.RingBufferFields.<clinit>(RingBuffer.java:34)
    at com.lmax.disruptor.dsl.Disruptor.<init>(Disruptor.java:137)
    at org.apache.logging.log4j.core.async.AsyncLoggerConfigDisruptor.start(AsyncLoggerConfigDisruptor.java:220)
    at org.apache.logging.log4j.core.config.AbstractConfiguration.start(AbstractConfiguration.java:312)
    at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:621)
    at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:694)
    at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:711)
    at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:253)
    at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:155)
    at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:47)
    at org.apache.logging.log4j.LogManager.getContext(LogManager.java:196)
    at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:599)
    at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:585)
    at Main.<clinit>(Main.java:25)
Caused by: java.lang.ClassNotFoundException: sun.misc.Unsafe
    at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
    at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
    at java.base/java.lang.ClassLoader.loadClass(Unknown Source)

```

**Comment by jvz** [comment]
Might be related to #1829.

**Comment by jvz** [comment]
This might show up elsewhere in Log4j, actually, so it's not entirely solved by an LMAX upgrade here. This issue can be expanded to any other `sun.misc.Unsafe` usage (I'm pretty sure the mmap appender uses it amongst others).

**Comment by jkvargas** [comment]
hi @jvz ,
I am trying to reproduce the issue with the smallest app possible running on ubuntu linux with java 21 and version 2.+

app is quite simple:

package reproduce;

```
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

public class App {
    private static Logger logger = LogManager.getLogger();

    public static void main(String[] args) {
        logger.info("test");
    }
}
```

and this is the config file.


```
<?xml version="1.0" encoding="UTF-8"?>
<Configuration status="INFO">
    <Appenders>
        <!-- Define a Console appender -->
        <Console name="Console" target="SYSTEM_OUT">
            <PatternLayout pattern="%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"/>
        </Console>

        <!-- Wrap the Console appender with AsyncAppender -->
        <Async name="Async">
            <AppenderRef ref="Console"/>
        </Async>
    </Appenders>

    <!-- Use the AsyncAppender as the root logger -->
    <Loggers>
        <Root level="debug">
            <AppenderRef ref="Async"/>
        </Root>
    </Loggers>
</Configuration>
```

this does not seem to cause any issues.
What exactly is what triggers the problem?

**Comment by jvz** [comment]
The trigger for this particular issue is that somewhere in LMAX, it uses `sun.misc.Unsafe` without catching `java.lang.NoClassDefFoundError` at the call site where they load it. You need to add that dependency to the class path to reproduce this.

**Comment by ppkarwasz** [comment]
`sun.misc.Unsafe` was removed from LMAX Disruptor two years ago: https://github.com/LMAX-Exchange/disruptor/commit/63f9abca5228380202b44b44c2b166205179b1d1

Version 4.0.0 should run without problems (once we add support for 4.x).
