### ISSUE TITLE
[3.0.0-beta1] reflect.TargetInvocationReflection when run from uber jar

### ISSUE THREAD

**Issue by riwarek** [apache/logging-log4j2#2179]
I see such exception:
`Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:62)
Caused by: java.lang.NoClassDefFoundError: org/apache/logging/log4j/LogManager
        at rmdev.scolog.log.Log.getLogger(Log.java:48)
        at rmdev.scolog.SCoLog.handleInputParameters(SCoLog.java:93)
        at rmdev.scolog.SCoLog.main(SCoLog.java:33)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        ... 2 more
Caused by: java.lang.ClassNotFoundException: org.apache.logging.log4j.LogManager
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:593)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
        ... 6 more`

when I tried to run app with jar-in-jar-loader created by Eclipse 2023-12 (using Oracle jdk21).

Content of MANIFEST.FM file is:
`Manifest-Version: 1.0
Ant-Version: Apache Ant 1.10.14
Created-By: 21+35-LTS-2513 (Oracle Corporation)
Main-Class: org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader
Rsrc-Main-Class: rmdev.scolog.SCoLog
Rsrc-Class-Path: ./ lib/log4j/log4j-api-3.0.-beta1.jar lib/log4j/log4j
 -core-3.0.-beta1.jar lib/log4j/log4j-plugins-3.0.-beta1.jar lib/jdate
 picker-1.3.4.jar
Class-Path: .`

All expected files (including jars) are in places in main jar file.

**Comment by ppkarwasz** [comment]
@riwarek,

Thank you very much for the report. We'll look into that.

To add some context to other contributors, this was by [your question on SO](https://stackoverflow.com/q/77787599/11748454). The failure of the `jar-in-jar` loader with Log4j 2.x is due to eclipse-jdt/eclipse.jdt.ui#1057, but for Log4j 3.x this can very well be a Log4j bug.

**Comment by riwarek** [comment]
@ppkarwasz 
Yes you are right, this is the fork of my problem presented on SO.

**Comment by ppkarwasz** [comment]
@riwarek,

I can not reproduce the issue. I created a `2179_log4j_3.x` in [copernik-eu/bug-reproducibility/eclipse-jar-in-jar](https://github.com/copernik-eu/bug-reproducibility/tree/2179_log4j_3.x/eclipse-jar-in-jar) with a sample project. It works both from Maven and Eclipse.

I think Eclipse might be messing with the `RsrcClasspath`. You have:

```
Rsrc-Class-Path: ./ lib/log4j/log4j-api-3.0.-beta1.jar lib/log4j/log4j-core-3.0.-beta1.jar lib/log4j/log4j-plugins-3.0.-beta1.jar lib/jdatepicker-1.3.4.jar
```

whereas it should be:

```
Rsrc-Class-Path: ./ log4j-api-3.0.-beta1.jar log4j-core-3.0.-beta1.jar log4j-plugins-3.0.-beta1.jar jdatepicker-1.3.4.jar
```

**Comment by riwarek** [comment]
@ppkarwasz
No this is ok.
This is part of my ant script:

`
	
	
	<target name="build of JAR" depends="preparation">
		<jar destfile="${OUT_DIR}\${APP_NAME}.jar">
			<manifest>
				<attribute name="Main-Class" value="org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader" />
				<attribute name="Rsrc-Main-Class" value="rmdev.scolog.SCoLog" />
				<attribute name="Class-Path" value="." />
				<attribute name="Rsrc-Class-Path" value="./ lib/log4j/log4j-api-3.0.-beta1.jar lib/log4j/log4j-core-3.0.-beta1.jar lib/log4j/log4j-plugins-3.0.-beta1.jar lib/jdatepicker-1.3.4.jar" />
				
			</manifest>
			<zipfileset src="jar-in-jar-loader.zip" />
			
			<zipfileset dir="${WORKSPACE_DIR}\${PROJECT_NAME}\lib" includes="**/*.jar" prefix="lib" />
			<fileset dir="../bin" />
		</jar>
	</target>`

And this is structure of my libs in project:
![obraz](https://github.com/apache/logging-log4j2/assets/22499151/930d7ab2-e6c2-4345-89c9-b31239f453b7)

And this is eclipse 'configure build path':
![obraz](https://github.com/apache/logging-log4j2/assets/22499151/ebe7cbf8-49a7-405c-a4da-19e6a042e00c)

Simply speaking I forced all libs to be in /lib in uberjar to avioid mess caused by presence of jars in root of uberjar.

**Comment by riwarek** [comment]
Just for clarification, earlier I used this pattern with uberjar and I had proper results.
It worked with configuration log4j-api-2.2 and oracle jdk1.8

**Comment by ppkarwasz** [comment]
@riwarek,

You have a typo in your script:

```xml
<attribute name="Rsrc-Class-Path" value="./ lib/log4j/log4j-api-3.0.-beta1.jar lib/log4j/log4j-core-3.0.-beta1.jar lib/log4j/log4j-plugins-3.0.-beta1.jar lib/jdatepicker-1.3.4.jar" />
```

should be:

```xml
<attribute name="Rsrc-Class-Path" value="./ lib/log4j/log4j-api-3.0.0-beta1.jar lib/log4j/log4j-core-3.0.0-beta1.jar lib/log4j/log4j-plugins-3.0.0-beta1.jar lib/jdatepicker-1.3.4.jar" />
```

**Comment by riwarek** [comment]
FACEPALM
Damn - you are right! How could I miss it?!
This solves the issue with 3.0.0. Now I can runn app with success.

Anyway we can state that for jar-in-jar from newest eclipse everything works as expected. I'm sorry for bothering you wiht my blindness and thank you for your time.
