### ISSUE TITLE
Unhandled `ServiceLoader` failure

### ISSUE THREAD

**Issue by ppkarwasz** [apache/logging-log4j2#2252]
While running on JVM 17, I encountered yet another exception that can arise from `ServiceLoader` and we don't catch it:

```
java.lang.NullPointerException: Cannot invoke "java.util.Enumeration.hasMoreElements()" because "this.configs" is null
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1210)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1228)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1273)
	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1309)
	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1393)
	at org.apache.logging.log4j.util.ServiceLoaderUtil$ServiceLoaderSpliterator.tryAdvance(ServiceLoaderUtil.java:161)
```

**Comment by ppkarwasz** [comment]
## How to reproduce

This happens in the tests of my [`copernik-eu/log4j-plugins`](https://github.com/copernik-eu/log4j-plugins) were I use Mockito to mock the TCCL, so it might be a bug in the test.

However, we should consider adding NPE to the list of exceptions caught by `ServiceLoaderSpliterator`.

**Comment by ppkarwasz** [comment]
This was caused by using a mock as classloader, so I am closing it.
