### ISSUE TITLE
[Fatal Error] log4j2.yml:1:1: Content is not allowed in prolog.

### ISSUE THREAD

**Issue by sysmat** [apache/logging-log4j2#2318]
## Description

- using this for conf https://logging.apache.org/log4j/2.x/manual/configuration.html#YAML

## Configuration

**Version:** 2.23.0

**Operating system:** Win 11

**JDK:** 21

## Logs

```
[Fatal Error] log4j2.yml:1:1: Content is not allowed in prolog.
|#]
	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:262)
	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
	at org.apache.logging.log4j.core.config.xml.XmlConfiguration.<init>(XmlConfiguration.java:92)
	at org.apache.logging.log4j.core.config.xml.XmlConfigurationFactory.getConfiguration(XmlConfigurationFactory.java:46)
	at org.apache.logging.log4j.core.config.ConfigurationFactory$Factory.getConfiguration(ConfigurationFactory.java:506)
	at org.apache.logging.log4j.core.config.ConfigurationFactory$Factory.getConfiguration(ConfigurationFactory.java:481)
	at org.apache.logging.log4j.core.config.ConfigurationFactory$Factory.getConfiguration(ConfigurationFactory.java:402)
	at org.apache.logging.log4j.core.config.ConfigurationFactory.getConfiguration(ConfigurationFactory.java:321)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:705)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:735)
	at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:260)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:154)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:46)
	at org.apache.logging.log4j.LogManager.getContext(LogManager.java:197)
	at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getContext(AbstractLoggerAdapter.java:136)
	at org.apache.logging.slf4j.Log4jLoggerFactory.getContext(Log4jLoggerFactory.java:58)
	at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getLogger(AbstractLoggerAdapter.java:46)
	at org.apache.logging.slf4j.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:32)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:422)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:447)
	at si.arnes.utils.db.ArnesBean.<clinit>(ArnesBean.java:27)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
```

## Reproduction

[An isolated test reproducing the test.
JUnit tests similar to the ones in the code base are extremely appreciated.]

**Comment by rgoers** [comment]
YAML support requires that the following classes be available on the classpath
```
        "com.fasterxml.jackson.databind.ObjectMapper",
        "com.fasterxml.jackson.databind.JsonNode",
        "com.fasterxml.jackson.core.JsonParser",
        "com.fasterxml.jackson.dataformat.yaml.YAMLFactory"
```
If any of them are not found then the YamlConfigurationFactory is ignored and the default XmlConfigurationFactory is used. 

We could probably handle this better.

**Comment by ppkarwasz** [comment]
This is related to #2352.
