### ISSUE TITLE
java.lang.IllegalArgumentException with ParameterFormatter.formatMessage when handle json

### ISSUE THREAD

**Issue by hpcnx** [apache/logging-log4j2#2323]
## Description

When doing logj42 logging:  '{"key":{}}'
saw exception like this:
Caused by: java.lang.IllegalArgumentException: found 1 argument placeholders, but provided 0 for pattern 
It does not happen with log4j 

Have not seen related issue reported or fixed yet. 
Could you please share any information if the issue had been fixed another newer log4j2?

Thanks

## Configuration

**Version:** [Log4j version]
log4j-core-2.21.1.jar
**Operating system:** [OS and version]
Microsoft Windows [Version 10.0.17763.5458]

**JDK:** [JDK distribution and version]
openjdk version "17.0.7" 2023-04-18 LTS

## Logs

```
[Stacktraces, errors, etc. relevant applications logs.]
Caused by: java.lang.IllegalArgumentException: found 1 argument placeholders, but provided 0 for pattern `(new String("{\"key\":{}}"))`
	at org.apache.logging.log4j.message.ParameterFormatter.formatMessage(ParameterFormatter.java:238) ~[log4j-api-2.21.1.jar:?]
	at org.apache.logging.log4j.message.ParameterizedMessage.formatTo(ParameterizedMessage.java:261) ~[log4j-api-2.21.1.jar:?]
	at org.apache.logging.log4j.core.pattern.MessagePatternConverter$SimpleMessagePatternConverter.format(MessagePatternConverter.java:121) ~[log4j-core-2.21.1.jar:?]
	at org.apache.logging.log4j.core.layout.PatternLayout$NoFormatPatternSerializer.toSerializable(PatternLayout.java:342) ~[log4j-core-2.21.1.jar:?]
	at org.apache.logging.log4j.core.layout.PatternLayout.toText(PatternLayout.java:240) ~[log4j-core-2.21.1.jar:?]
	at org.apache.logging.log4j.core.layout.PatternLayout.encode(PatternLayout.java:225) ~[log4j-core-2.21.1.jar:?]
	at org.apache.logging.log4j.core.layout.PatternLayout.encode(PatternLayout.java:59) ~[log4j-core-2.21.1.jar:?]
	at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.directEncodeEvent(AbstractOutputStreamAppender.java:219) ~[log4j-core-2.21.1.jar:?]
	at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.tryAppend(AbstractOutputStreamAppender.java:212) ~[log4j-core-2.21.1.jar:?]
	at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.append(AbstractOutputStreamAppender.java:203) ~[log4j-core-2.21.1.jar:?]
	at org.apache.logging.log4j.core.appender.RollingFileAppender.append(RollingFileAppender.java:301) ~[log4j-core-2.21.1.jar:?]
	at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:161) ~[log4j-core-2.21.1.jar:?]
	at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:134) ~[log4j-core-2.21.1.jar:?]
	at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:125) ~[log4j-core-2.21.1.jar:?]
	at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:89) ~[log4j-core-2.21.1.jar:?]
	at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:686) ~[log4j-core-2.21.1.jar:?]
	at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:644) ~[log4j-core-2.21.1.jar:?]
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:620) ~[log4j-core-2.21.1.jar:?]
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:556) ~[log4j-core-2.21.1.jar:?]
	at org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:81) ~[log4j-core-2.21.1.jar:?]
	at org.apache.logging.log4j.core.Logger.log(Logger.java:163) ~[log4j-core-2.21.1.jar:?]
	at org.apache.logging.log4j.spi.AbstractLogger.tryLogMessage(AbstractLogger.java:2165) ~[log4j-api-2.21.1.jar:?]
	at org.apache.logging.log4j.spi.AbstractLogger.logMessageTrackRecursion(AbstractLogger.java:2119) ~[log4j-api-2.21.1.jar:?]
	at org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2102) ~[log4j-api-2.21.1.jar:?]
	at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:1988) ~[log4j-api-2.21.1.jar:?]
	at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1851) ~[log4j-api-2.21.1.jar:?]
	at org.apache.logging.log4j.spi.AbstractLogger.info(AbstractLogger.java:1285) ~[log4j-api-2.21.1.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:126) ~[rhino-1.7.7.1.jar:1.7.7.1]


## Reproduction

[An isolated test reproducing the test.
JUnit tests similar to the ones in the code base are extremely appreciated.]

**Comment by ppkarwasz** [comment]
Hi @hpcnx,

Can you provide the source code of your logging call?

According to the stacktrace, you are calling `info(String, Object...)` instead of `info(String)`:

https://github.com/apache/logging-log4j2/blob/e613e9ed71279bb52753a4df810d61c11389df81/log4j-api/src/main/java/org/apache/logging/log4j/spi/AbstractLogger.java#L1283-L1286

The difference between the two is subtle: the former call uses parameterized logging (cf. [documentation](https://logging.apache.org/log4j/2.x/manual/messages.html)) and interprets all `{}` sequences as placeholders. The latter should print the string **as is**.

Can you also provide all the exceptions? The `IllegalArgumentException` itself should not propagate to the user, but the exception **caused by it** might.

**Comment by hpcnx** [comment]
Thanks for looking into this!

Here is the exception:

Caused by: java.lang.IllegalArgumentException: found 1 argument placeholders, but provided 0 for pattern `(new String("{\"key\":{}}"))`
	at org.apache.logging.log4j.message.ParameterFormatter.formatMessage(ParameterFormatter.java:238) ~[log4j-api-2.21.1.jar:?]
	at org.apache.logging.log4j.message.ParameterizedMessage.formatTo(ParameterizedMessage.java:261) ~[log4j-api-2.21.1.jar:?]
	at org.apache.logging.log4j.core.pattern.MessagePatternConverter$SimpleMessagePatternConverter.format(MessagePatternConverter.java:121) ~[log4j-core-2.21.1.jar:?]
	at org.apache.logging.log4j.core.layout.PatternLayout$NoFormatPatternSerializer.toSerializable(PatternLayout.java:342) ~[log4j-core-2.21.1.jar:?]
	at org.apache.logging.log4j.core.layout.PatternLayout.toText(PatternLayout.java:240) ~[log4j-core-2.21.1.jar:?]
	at org.apache.logging.log4j.core.layout.PatternLayout.encode(PatternLayout.java:225) ~[log4j-core-2.21.1.jar:?]
	at org.apache.logging.log4j.core.layout.PatternLayout.encode(PatternLayout.java:59) ~[log4j-core-2.21.1.jar:?]
	at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.directEncodeEvent(AbstractOutputStreamAppender.java:219) ~[log4j-core-2.21.1.jar:?]
	at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.tryAppend(AbstractOutputStreamAppender.java:212) ~[log4j-core-2.21.1.jar:?]
	at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.append(AbstractOutputStreamAppender.java:203) ~[log4j-core-2.21.1.jar:?]
	at org.apache.logging.log4j.core.appender.RollingFileAppender.append(RollingFileAppender.java:301) ~[log4j-core-2.21.1.jar:?]
	at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:161) ~[log4j-core-2.21.1.jar:?]
	at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:134) ~[log4j-core-2.21.1.jar:?]
	at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:125) ~[log4j-core-2.21.1.jar:?]
	at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:89) ~[log4j-core-2.21.1.jar:?]
	at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:686) ~[log4j-core-2.21.1.jar:?]
	at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:644) ~[log4j-core-2.21.1.jar:?]
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:620) ~[log4j-core-2.21.1.jar:?]
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:556) ~[log4j-core-2.21.1.jar:?]
	at org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:81) ~[log4j-core-2.21.1.jar:?]
	at org.apache.logging.log4j.core.Logger.log(Logger.java:163) ~[log4j-core-2.21.1.jar:?]
	at org.apache.logging.log4j.spi.AbstractLogger.tryLogMessage(AbstractLogger.java:2165) ~[log4j-api-2.21.1.jar:?]
	at org.apache.logging.log4j.spi.AbstractLogger.logMessageTrackRecursion(AbstractLogger.java:2119) ~[log4j-api-2.21.1.jar:?]
	at org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2102) ~[log4j-api-2.21.1.jar:?]
	at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:1988) ~[log4j-api-2.21.1.jar:?]
	at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1851) ~[log4j-api-2.21.1.jar:?]
	at org.apache.logging.log4j.spi.AbstractLogger.info(AbstractLogger.java:1285) ~[log4j-api-2.21.1.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:126) ~[rhino-1.7.7.1.jar:1.7.7.1]
	at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:225) ~[rhino-1.7.7.1.jar:1.7.7.1]
	at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1479) ~[rhino-1.7.7.1.jar:1.7.7.1]
	at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:815) ~[rhino-1.7.7.1.jar:1.7.7.1]
	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109) ~[rhino-1.7.7.1.jar:1.7.7.1]
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:393) ~[rhino-1.7.7.1.jar:1.7.7.1]
	at com.intervoice.scxml.runtime.language.ecmascript.RhinoContext$CustomContextFactory.doTopCall(RhinoContext.java:3185) ~[com.intervoice.scxml.runtime.core_13.0.0.202402262224.jar:?]
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3282) ~[rhino-1.7.7.1.jar:1.7.7.1]
	at org.mozilla.javascript.InterpretedFunction.exec(InterpretedFunction.java:120) ~[rhino-1.7.7.1.jar:1.7.7.1]
	at com.intervoice.scxml.runtime.language.ecmascript.RhinoContext.cachedEvaluate(RhinoContext.java:1279) ~[com.intervoice.scxml.runtime.core_13.0.0.202402262224.jar:?]
	at com.intervoice.scxml.runtime.language.ecmascript.RhinoContext.evaluateNonSerializable(RhinoContext.java:1389) ~[com.intervoice.scxml.runtime.core_13.0.0.202402262224.jar:?]
	at com.intervoice.scxml.runtime.internal.model.Script.doStartAction(Script.java:222) ~[com.intervoice.scxml.runtime.core_13.0.0.202402262224.jar:?]
	... 17 more

Here is some code:
public synchronized ILogger getLogger(String name)
{
	  final LoggerContextFactory factory = LogManager.getFactory();
	  if (factory instanceof Log4jContextFactory) {
	    final ContextSelector selector = ((Log4jContextFactory) factory).getSelector();
	    if (selector instanceof CustomContextSelector) {
	    	CustomContextSelector namedContextSelector = (CustomContextSelector) selector;
	    	CustomLoggerContext ctx = namedContextSelector.locateContext(loggerContext.getName(),loggerContext.getName(),loggerContext.getConfigLocation());
	    	return (ILogger)ctx.getLogger(name);
	    }
	  }
	  ILogger logger = (ILogger) LogManager.getLogger(name);
	 return logger;
}

public class CustomLoggerContext extends LoggerContext {

    private static final long serialVersionUID = 1L;

    public CustomLoggerContext(String name) {
        super(name);
    }
    public CustomLoggerContext(  String name,  Object externalContext,  URI configLocn) {
    	super(name,externalContext,configLocn);
    }
    @Override
    protected Logger newInstance(final LoggerContext ctx, final String name, final MessageFactory messageFactory) {
        return new CustomLogger(ctx, name, messageFactory);
    }  
}

public class CustomLogger extends Logger implements ILogger {
    private static final String FQCN = CustomLogger.class.getName();
    protected CustomLogger(LoggerContext context, String name, MessageFactory messageFactory) {
        super(context, name, messageFactory);
    }

    public void info(CustomLogMessage logMessage) {
     logIfEnabled(FQCN, Level.INFO, null, logMessage, null);
    }
...
}

The application is doing script to log info(message).
var data = '{"key":{}}';
Packages.com.intervoice.scxml.runtime.logging.LoggerUtil.getUserLogger("myLogger").info(data.toSource());

Only when data contains {} as value it throws the exception.

**Comment by vy** [comment]
@hpcnx, could you share the sources of `com.intervoice.scxml.runtime.logging.LoggerUtil` too, please?

**Comment by hpcnx** [comment]
package com.intervoice.logging;

import java.lang.reflect.Array;
import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationTargetException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;
import java.util.Enumeration;
import java.util.Formatter;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;
import org.apache.logging.log4j.Level;

public class LoggerUtil
{
  public static String formatMessage(String message, Object... varargs)
  {
    Formatter formatter = new Formatter();
    
    ArrayList<Object> formattableArgs = new ArrayList(varargs.length);
    Object[] arrayOfObject;
    int j = (arrayOfObject = varargs).length;
    for (int i = 0; i < j; i++)
    {
      Object varg = arrayOfObject[i];
      if (varg != null)
      {
        Class<?> varclass = varg.getClass();
        if ((varclass.isArray()) || 
          (Collection.class.isAssignableFrom(varclass)) || 
          (Map.class.isAssignableFrom(varclass)) || 
          (Map.Entry.class.isAssignableFrom(varclass))) {
          formattableArgs.add(new DeepFormatter(varg));
        } else {
          formattableArgs.add(varg);
        }
      }
      else
      {
        formattableArgs.add(varg);
      }
    }
    String formattedMessage = null;
    try
    {
      formattedMessage = formatter.format(message, formattableArgs.toArray()).toString();
    }
    catch (Exception e)
    {
      getConfigLogger(LoggerUtil.class).warn("Could not format message", e);
      formattedMessage = "Unable to format log message: " + e.getMessage();
    }
    return formattedMessage;
  }
  
  public static void logf(ILogger logger, Level level, String message, Object... varargs)
  {
    if (logger.isEnabledFor(level)) {
      logger.log(level, formatMessage(message, varargs));
    }
  }
  
  public static void logf(IPrivacyAware privatizable, ILogger logger, Level level, String message, Object... varargs)
  {
    if ((privatizable == null) || (!privatizable.isPrivate())) {
      logf(logger, level, message, varargs);
    }
  }
  
  public static void logf(ILogger logger, Level level, String message, Throwable t, Object... varargs)
  {
    if (logger.isEnabledFor(level)) {
      logger.log(level, formatMessage(message, varargs), t);
    }
  }
  
  public static void logf(IPrivacyAware privatizable, ILogger logger, Level level, String message, Throwable t, Object... varargs)
  {
    if ((privatizable == null) || (!privatizable.isPrivate())) {
      logf(logger, level, message, t, varargs);
    }
  }
  
  public static void fatalf(ILogger logger, String message, Object... varargs)
  {
    if (logger.isFatalEnabled()) {
      logger.fatal(formatMessage(message, varargs));
    }
  }
  
  public static void fatalf(IPrivacyAware privatizable, ILogger logger, String message, Object... varargs)
  {
    if ((privatizable == null) || (!privatizable.isPrivate())) {
      fatalf(logger, message, varargs);
    }
  }
  
  public static void fatalf(ILogger logger, String message, Throwable t, Object... varargs)
  {
    if (logger.isFatalEnabled()) {
      logger.fatal(formatMessage(message, varargs), t);
    }
  }
  
  public static void fatalf(IPrivacyAware privatizable, ILogger logger, String message, Throwable t, Object... varargs)
  {
    if ((privatizable == null) || (!privatizable.isPrivate())) {
      fatalf(logger, message, t, varargs);
    }
  }
  
  public static void errorf(ILogger logger, String message, Object... varargs)
  {
    if (logger.isErrorEnabled()) {
      logger.error(formatMessage(message, varargs));
    }
  }
  
  public static void errorf(IPrivacyAware privatizable, ILogger logger, String message, Object... varargs)
  {
    if ((privatizable == null) || (!privatizable.isPrivate())) {
      errorf(logger, message, varargs);
    }
  }
  
  public static void errorf(ILogger logger, String message, Throwable t, Object... varargs)
  {
    if (logger.isErrorEnabled()) {
      logger.error(formatMessage(message, varargs), t);
    }
  }
  
  public static void errorf(IPrivacyAware privatizable, ILogger logger, String message, Throwable t, Object... varargs)
  {
    if ((privatizable == null) || (!privatizable.isPrivate())) {
      errorf(logger, message, t, varargs);
    }
  }
  
  public static void warnf(ILogger logger, String message, Object... varargs)
  {
    if (logger.isWarnEnabled()) {
      logger.warn(formatMessage(message, varargs));
    }
  }
  
  public static void warnf(IPrivacyAware privatizable, ILogger logger, String message, Object... varargs)
  {
    if ((privatizable == null) || (!privatizable.isPrivate())) {
      warnf(logger, message, varargs);
    }
  }
  
  public static void warnf(ILogger logger, String message, Throwable t, Object... varargs)
  {
    if (logger.isWarnEnabled()) {
      logger.warn(formatMessage(message, varargs), t);
    }
  }
  
  public static void warnf(IPrivacyAware privatizable, ILogger logger, String message, Throwable t, Object... varargs)
  {
    if ((privatizable == null) || (!privatizable.isPrivate())) {
      warnf(logger, message, t, varargs);
    }
  }
  
  public static void infof(ILogger logger, String message, Object... varargs)
  {
    if (logger.isInfoEnabled()) {
      logger.info(formatMessage(message, varargs));
    }
  }
  
  public static void infof(IPrivacyAware privatizable, ILogger logger, String message, Object... varargs)
  {
    if ((privatizable == null) || (!privatizable.isPrivate())) {
      infof(logger, message, varargs);
    }
  }
  
  public static void infof(ILogger logger, String message, Throwable t, Object... varargs)
  {
    if (logger.isInfoEnabled()) {
      logger.info(formatMessage(message, varargs), t);
    }
  }
  
  public static void infof(IPrivacyAware privatizable, ILogger logger, String message, Throwable t, Object... varargs)
  {
    if ((privatizable == null) || (!privatizable.isPrivate())) {
      infof(logger, message, t, varargs);
    }
  }
  
  public static void debugf(ILogger logger, String message, Object... varargs)
  {
    if (logger.isDebugEnabled()) {
      logger.debug(formatMessage(message, varargs));
    }
  }
  
  public static void debugf(IPrivacyAware privatizable, ILogger logger, String message, Object... varargs)
  {
    if ((privatizable == null) || (!privatizable.isPrivate())) {
      debugf(logger, message, varargs);
    }
  }
  
  public static void debugf(ILogger logger, String message, Throwable t, Object... varargs)
  {
    if (logger.isDebugEnabled()) {
      logger.debug(formatMessage(message, varargs), t);
    }
  }
  
  public static void debugf(IPrivacyAware privatizable, ILogger logger, String message, Throwable t, Object... varargs)
  {
    if ((privatizable == null) || (!privatizable.isPrivate())) {
      debugf(logger, message, t, varargs);
    }
  }
  
  public static void tracef(ILogger logger, String message, Object... varargs)
  {
    if (logger.isTraceEnabled()) {
      logger.trace(formatMessage(message, varargs));
    }
  }
  
  public static void tracef(IPrivacyAware privatizable, ILogger logger, String message, Object... varargs)
  {
    if ((privatizable == null) || (!privatizable.isPrivate())) {
      tracef(logger, message, varargs);
    }
  }
  
  public static void tracef(ILogger logger, String message, Throwable t, Object... varargs)
  {
    if (logger.isTraceEnabled()) {
      logger.trace(formatMessage(message, varargs), t);
    }
  }
  
  public static void tracef(IPrivacyAware privatizable, ILogger logger, String message, Throwable t, Object... varargs)
  {
    if ((privatizable == null) || (!privatizable.isPrivate())) {
      tracef(logger, message, t, varargs);
    }
  }
  
  public static String expandObjectToString(Object o)
  {
    StringBuilder sb = build(o, new StringBuilder());
    return sb.toString();
  }
  
  private static StringBuilder build(Object o, StringBuilder builder)
  {
    try
    {
      if (o == null)
      {
        builder.append("null");
      }
      else if (o.getClass().isArray())
      {
        build(Arrays.asList(toObjectArray(o)), builder);
      }
      else if ((o instanceof Iterator))
      {
        Iterator<?> iter = (Iterator)o;
        builder.append("[");
        while (iter.hasNext())
        {
          builder.append(" ");
          build(iter.next(), builder);
        }
        builder.append(" ]");
      }
      else if ((o instanceof Enumeration))
      {
        Enumeration<?> enumer = (Enumeration)o;
        builder.append("[");
        while (enumer.hasMoreElements())
        {
          builder.append(" ");
          build(enumer.nextElement(), builder);
        }
        builder.append(" ]");
      }
      else if ((o instanceof Collection))
      {
        build(((Collection)o).iterator(), builder);
      }
      else if ((o instanceof Map))
      {
        build(((Map)o).entrySet().iterator(), builder);
      }
      else if ((o instanceof Map.Entry))
      {
        Map.Entry<?, ?> entry = (Map.Entry)o;
        build(entry.getKey(), builder);
        builder.append("=");
        build(entry.getValue(), builder);
      }
      else
      {
        builder.append(o);
      }
    }
    catch (Exception ex)
    {
      getConfigLogger(LoggerUtil.class).warn("Caught while formatting Logger output", ex);
      builder.append(ex.getClass().getName())
        .append(" caught while building output for ");
      if (o == null) {
        builder.append("a null object reference");
      } else {
        builder.append(o.getClass().getName()).append("@").append(Integer.toHexString(System.identityHashCode(o)));
      }
      builder.append(": ").append(ex.getMessage());
    }
    return builder;
  }
  
  static
  {
    WRAPPER_CLASSES.put(Integer.TYPE, Integer.class);
    WRAPPER_CLASSES.put(Long.TYPE, Long.class);
    WRAPPER_CLASSES.put(Short.TYPE, Short.class);
    WRAPPER_CLASSES.put(Byte.TYPE, Byte.class);
    WRAPPER_CLASSES.put(Float.TYPE, Float.class);
    WRAPPER_CLASSES.put(Double.TYPE, Double.class);
    WRAPPER_CLASSES.put(Character.TYPE, Character.class);
    WRAPPER_CLASSES.put(Boolean.TYPE, Boolean.class);
  }
  
  private static Object[] toObjectArray(Object array)
  {
    Class<?> objectClass = array.getClass();
    Class<?> componentType = objectClass.getComponentType();
    
    Object[] retval = null;
    if (componentType.isPrimitive())
    {
      Class<?> wrapperType = (Class)WRAPPER_CLASSES.get(componentType);
      try
      {
        Constructor<?> oneArgInit = wrapperType.getConstructor(new Class[] { componentType });
        retval = new Object[Array.getLength(array)];
        for (int i = 0; i < retval.length; i++) {
          retval[i] = oneArgInit.newInstance(new Object[] { Array.get(array, i) });
        }
      }
      catch (NoSuchMethodException localNoSuchMethodException) {}catch (InstantiationException localInstantiationException) {}catch (IllegalAccessException localIllegalAccessException) {}catch (InvocationTargetException localInvocationTargetException) {}
    }
    else
    {
      retval = (Object[])array;
    }
    return retval;
  }
  
  private static class DeepFormatter
  {
    private Object target;
    
    DeepFormatter(Object target)
    {
      this.target = target;
    }
    
    public String toString()
    {
      return LoggerUtil.expandObjectToString(this.target);
    }
  }
  
  public static ILogger getLogger(Class<?> clazz)
  {
	  return null;
  }
  
  public static ILogger getLogger(String loggerName)
  {
	  return null;
  }
  
  public static ILogger getUserLogger(Class<?> clazz)
  {
    String loggerName = "StateControl.User";
    if (clazz != null)
    {
      String className = clazz.getName();
      if (className.length() > 0) {
        loggerName = loggerName + "." + className;
      }
    }
    return getLogger(loggerName);
  }
  
  public static ILogger getUserLogger(String name)
  {
    String loggerName = "StateControl.User";
    if ((name != null) && (name.trim().length() > 0)) {
      loggerName = loggerName + "." + name.trim();
    }
    return getLogger(loggerName);
  }
 
}

**Comment by vy** [comment]
@hpcnx, I am not able to understand how does your `logger.info("foo {}")` call in JavaScript gets translated to `logger.info("foo {}", new Object[0])` in Java. The following works for me:

```
import javax.script.ScriptEngine;
import javax.script.ScriptEngineManager;
import javax.script.ScriptException;

public class Issue2323 {
    public static void main(String[] args) throws ScriptException {
        ScriptEngine engine = new ScriptEngineManager().getEngineByName("nashorn");
        engine.eval("Packages.org.apache.logging.log4j.LogManager.getLogger().error('foo {}');");
    }
}
```

AFAIC, this is not a Log4j issue. If you think otherwise, please produce a *minimal* (where all necessary code is removed!) reproduction example.

I suspect something unexpected is going with your `CustomLogger` implementation. I suggest you to put a breakpoint into `AbstractLogger#info(String,Object[])` and try to figure out why doesn't `#info(String)` get called instead.
