### ISSUE TITLE
NPE when using `rootLogger` shorthand properties notation

### ISSUE THREAD

**Issue by ayush11-96** [apache/logging-log4j2#3206]
Currently we are using log4j2 version 2.17.0 with spring boot but while updating log4j2 to 2.17.2 we are getting below error and which is because of the appender of root is initialise to null
`Caused by: java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because the return value of "org.apache.logging.log4j.core.config.LoggerConfig.getAppenderRefs()" is null`

We are passing below properties:
```
rootLogger.appenderRef.console.ref=console
rootLogger.appenderRefs=console
rootLogger=INFO
```

Please help us to understand if we require some changes along with version upgrade?

**Comment by ppkarwasz** [comment]
@ayush11-96,

Does the problem also occur with version `2.24.1`?
Can you provide the full stack trace of the exception?

**Comment by ayush11-96** [comment]
@ppkarwasz 
I tried till 2.23.1 version and this is still happening
**Stack Trace:**
`Caused by: java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because the return value of "org.apache.logging.log4j.core.config.LoggerConfig.getAppenderRefs()" is null
	at org.apache.logging.log4j.core.config.AbstractConfiguration.doConfigure(AbstractConfiguration.java:740) ~[log4j-core-2.23.1.jar:2.23.1]
	at org.apache.logging.log4j.core.config.AbstractConfiguration.initialize(AbstractConfiguration.java:264) ~[log4j-core-2.23.1.jar:2.23.1]
	at org.apache.logging.log4j.core.config.AbstractConfiguration.start(AbstractConfiguration.java:313) ~[log4j-core-2.23.1.jar:2.23.1]
	at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:631) ~[log4j-core-2.23.1.jar:2.23.1]
	at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:292) ~[log4j-core-2.23.1.jar:2.23.1]`

**Comment by ayush11-96** [comment]
@ppkarwasz could u please elaborate the issue if u got that?

**Comment by ppkarwasz** [comment]
@ayush11-96,

There is problem in your configuration: you both use the shorthand `rootLogger = <level>, <ref1>, <ref2>` notation that was introduced in Log4j Core 2.17.2 IIRC (see [Properties configuration quirks](https://logging.apache.org/log4j/2.x/manual/configuration.html#java-properties-features) for more information) and the normal `rootLogger.appenderRef.<n>.ref` properties.
You should either use the long notation:

```properties
rootLogger.level = INFO
rootLogger.appenderRef.0.ref = console
```

or the shorthand notation (which only exists in the Java properties format):

```properties
rootLogger = INFO, console
```

The NPE is due to the fact that the current code does not handle the case, when the shorthand notation is used and no appender reference is provided (`rootLogger = INFO`). We will fix this in the next release.

**Comment by ayush11-96** [comment]
Thanks @ppkarwasz 
Can I expect any ETA for the new version with fix?

**Comment by ayush11-96** [comment]
thanks @ppkarwasz

**Comment by ppkarwasz** [comment]
I keep this open, so we can fix the NPE in the rare case a user really does not want any appenders attached to the root logger.

**Comment by jhl221123** [comment]
Hi @ppkarwasz,

I'd like to work on this `good first issue` regarding the NPE.

Since it's in 'To triage', please let me know if it's available for contribution.

Thanks!

**Comment by ppkarwasz** [comment]
@jhl221123,

Go ahead, thanks!

> Since it's in 'To triage', please let me know if it's available for contribution.

I introduced the [Log4j bug tracker](https://github.com/orgs/apache/projects/479), so many of the old reports are in the `To triage` state even if they were triaged before.

**Comment by injae-kim** [comment]
> fix PR: https://github.com/apache/logging-log4j2/pull/3650

can we close this issue cause fix PR is merged? 😄

**Comment by ppkarwasz** [comment]
@injae-kim,

Thanks, usually GitHub closes related issues automatically but apparently none of the [magic `close/fix/resolve` words](https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/linking-a-pull-request-to-an-issue) were used to link the PR to the issue.
